[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "qres"
version = "1.0.0"
description = "Quantum extreme learning and reservoir computing module"
authors = [{name="Matthew Mackinnon"}]
dependencies = [
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
